-- First, insert the House category
INSERT INTO categories (name, created_at, updated_at) 
VALUES ('House', NOW(), NOW());

-- Get the ID of the House category
SET @house_category_id = LAST_INSERT_ID();

-- Insert all inventory items for the House category
INSERT INTO inventory_items (item, category_id, cubic_ft, created_at, updated_at) VALUES
('Aerial/Dish', @house_category_id, 5, NOW(), NOW()),
('Air Conditioner', @house_category_id, 15, NOW(), NOW()),
('Art Work', @house_category_id, 4, NOW(), NOW()),
('Automobile', @house_category_id, 400, NOW(), NOW()),
('Van/Truck/SUV', @house_category_id, 500, NOW(), NOW()),
('Baby Bath', @house_category_id, 3, NOW(), NOW()),
('Baker''s Rack', @house_category_id, 5, NOW(), NOW()),
('Bags', @house_category_id, 4, NOW(), NOW()),
('Bar Stool', @house_category_id, 5, NOW(), NOW()),
('Barbecue', @house_category_id, 10, NOW(), NOW()),
('Bar, Portable', @house_category_id, 15, NOW(), NOW()),
('Basket', @house_category_id, 5, NOW(), NOW()),
('Bassinet', @house_category_id, 5, NOW(), NOW()),
('Bean Bag', @house_category_id, 6, NOW(), NOW()),
('Beauty Aids', @house_category_id, 2, NOW(), NOW()),
('Bed Frame', @house_category_id, 3, NOW(), NOW()),
('Bed Footboard', @house_category_id, 5, NOW(), NOW()),
('Bed Headboard', @house_category_id, 10, NOW(), NOW()),
('Bed, Roll-a-way', @house_category_id, 20, NOW(), NOW()),
('Bed, Child''s', @house_category_id, 30, NOW(), NOW()),
('Bed, Single', @house_category_id, 40, NOW(), NOW()),
('Bed, Double', @house_category_id, 60, NOW(), NOW()),
('Bed, Queen', @house_category_id, 65, NOW(), NOW()),
('Bed, King', @house_category_id, 70, NOW(), NOW()),
('Water bed part', @house_category_id, 10, NOW(), NOW()),
('Bed Bunk 2bd/set', @house_category_id, 70, NOW(), NOW()),
('Bedding', @house_category_id, 6, NOW(), NOW()),
('Bench', @house_category_id, 5, NOW(), NOW()),
('Bicycle', @house_category_id, 5, NOW(), NOW()),
('Bicycle,Exercise', @house_category_id, 7, NOW(), NOW()),
('Bird Bath', @house_category_id, 5, NOW(), NOW()),
('Bird Cage', @house_category_id, 5, NOW(), NOW()),
('Blackboard', @house_category_id, 5, NOW(), NOW()),
('Boat Trailer', @house_category_id, 100, NOW(), NOW()),
('Boat', @house_category_id, 35, NOW(), NOW()),
('Boat >14''', @house_category_id, 350, NOW(), NOW()),
('Bookcase', @house_category_id, 20, NOW(), NOW()),
('Books', @house_category_id, 2, NOW(), NOW()),
('Bookshelf', @house_category_id, 5, NOW(), NOW()),
('Box Spring', @house_category_id, 20, NOW(), NOW()),
('Breakfast Chair', @house_category_id, 5, NOW(), NOW()),
('Breakfast Table', @house_category_id, 10, NOW(), NOW()),
('Brooms, Etc.', @house_category_id, 1, NOW(), NOW()),
('Bucket', @house_category_id, 2, NOW(), NOW()),
('Buffet', @house_category_id, 30, NOW(), NOW()),
('Buffet (Top)', @house_category_id, 20, NOW(), NOW()),
('Buffet,Sideboard', @house_category_id, 30, NOW(), NOW()),
('Bureau', @house_category_id, 20, NOW(), NOW()),
('Cabinet, small', @house_category_id, 10, NOW(), NOW()),
('Cabinet, Curio', @house_category_id, 10, NOW(), NOW()),
('Cabinet', @house_category_id, 20, NOW(), NOW()),
('Cabinet, Corner', @house_category_id, 20, NOW(), NOW()),
('Cabinet, Metal', @house_category_id, 20, NOW(), NOW()),
('Cabinet, China', @house_category_id, 25, NOW(), NOW()),
('Cabinet, Large', @house_category_id, 35, NOW(), NOW()),
('Cabinet,Cocktail', @house_category_id, 40, NOW(), NOW()),
('Camper Shell', @house_category_id, 50, NOW(), NOW()),
('Camping Gear', @house_category_id, 15, NOW(), NOW()),
('Camper Trailer', @house_category_id, 700, NOW(), NOW()),
('Canoe', @house_category_id, 15, NOW(), NOW()),
('Canoe >14''', @house_category_id, 30, NOW(), NOW()),
('Car Seat', @house_category_id, 2, NOW(), NOW()),
('Card Table', @house_category_id, 2, NOW(), NOW()),
('Carpet, Small', @house_category_id, 3, NOW(), NOW()),
('Carpet', @house_category_id, 10, NOW(), NOW()),
('Chair Mat', @house_category_id, 1, NOW(), NOW()),
('Chair, Folding', @house_category_id, 1, NOW(), NOW()),
('Chair, Plastic', @house_category_id, 1, NOW(), NOW()),
('Chair, Child''s', @house_category_id, 3, NOW(), NOW()),
('Chair, Metal', @house_category_id, 3, NOW(), NOW()),
('Chair, Dining', @house_category_id, 5, NOW(), NOW()),
('Chair', @house_category_id, 8, NOW(), NOW()),
('Chair, Boudoir', @house_category_id, 10, NOW(), NOW()),
('Chair, Porch', @house_category_id, 10, NOW(), NOW()),
('Chair, Rocker', @house_category_id, 12, NOW(), NOW()),
('Chair,Occasional', @house_category_id, 15, NOW(), NOW()),
('Chair, Arm', @house_category_id, 10, NOW(), NOW()),
('Chair, Ovrstuffed', @house_category_id, 25, NOW(), NOW()),
('Chaise Lounge', @house_category_id, 15, NOW(), NOW()),
('Chandelier', @house_category_id, 6, NOW(), NOW()),
('Changing Table', @house_category_id, 15, NOW(), NOW()),
('Chest, Toy', @house_category_id, 5, NOW(), NOW()),
('Chest', @house_category_id, 12, NOW(), NOW()),
('Chest of Drawers', @house_category_id, 12, NOW(), NOW()),
('Chest, Armoire', @house_category_id, 30, NOW(), NOW()),
('China/Glass', @house_category_id, 4, NOW(), NOW()),
('Christmas Items', @house_category_id, 4, NOW(), NOW()),
('Clay Pot', @house_category_id, 2, NOW(), NOW()),
('Cleaning Items', @house_category_id, 4, NOW(), NOW()),
('Clock, G/Father', @house_category_id, 20, NOW(), NOW()),
('Closet Items', @house_category_id, 4, NOW(), NOW()),
('Clothes Dryer Rack', @house_category_id, 5, NOW(), NOW()),
('Clock', @house_category_id, 4, NOW(), NOW()),
('Dryer, Electric', @house_category_id, 25, NOW(), NOW()),
('Clothes Dryer', @house_category_id, 25, NOW(), NOW()),
('Dryer, Gas', @house_category_id, 25, NOW(), NOW()),
('Clothes Hamper', @house_category_id, 5, NOW(), NOW()),
('Clothes', @house_category_id, 5, NOW(), NOW()),
('Coat Rack', @house_category_id, 2, NOW(), NOW()),
('Computer Equip.', @house_category_id, 2, NOW(), NOW()),
('Range', @house_category_id, 20, NOW(), NOW()),
('Computer', @house_category_id, 4, NOW(), NOW()),
('Cooler', @house_category_id, 3, NOW(), NOW()),
('Computer Monitor', @house_category_id, 2, NOW(), NOW()),
('Copier', @house_category_id, 20, NOW(), NOW()),
('Cot, Folding', @house_category_id, 10, NOW(), NOW()),
('Credenza', @house_category_id, 20, NOW(), NOW()),
('Crib', @house_category_id, 10, NOW(), NOW()),
('Cot', @house_category_id, 12, NOW(), NOW()),
('Cupboard', @house_category_id, 20, NOW(), NOW()),
('Curtains', @house_category_id, 6, NOW(), NOW()),
('Desk Chair', @house_category_id, 5, NOW(), NOW()),
('Desk, Computer', @house_category_id, 22, NOW(), NOW()),
('Desk, small', @house_category_id, 22, NOW(), NOW()),
('Desk, Office', @house_category_id, 30, NOW(), NOW()),
('Desk', @house_category_id, 35, NOW(), NOW()),
('Dishes', @house_category_id, 4, NOW(), NOW()),
('Dishwasher', @house_category_id, 20, NOW(), NOW()),
('Dog House', @house_category_id, 10, NOW(), NOW()),
('Dresser, Vanity', @house_category_id, 20, NOW(), NOW()),
('Dresser', @house_category_id, 30, NOW(), NOW()),
('Dresser, Double', @house_category_id, 40, NOW(), NOW()),
('Dresser, Triple', @house_category_id, 50, NOW(), NOW()),
('Dried Flowers', @house_category_id, 4, NOW(), NOW()),
('Trash Can', @house_category_id, 7, NOW(), NOW()),
('Entertainmnt Cntr', @house_category_id, 25, NOW(), NOW()),
('Exercise Equip.', @house_category_id, 15, NOW(), NOW()),
('Fan', @house_category_id, 5, NOW(), NOW()),
('Farm Equipment', @house_category_id, 350, NOW(), NOW()),
('FAX', @house_category_id, 4, NOW(), NOW()),
('File Cabinet', @house_category_id, 10, NOW(), NOW()),
('File, Lateral', @house_category_id, 20, NOW(), NOW()),
('File Cab, 2-3 dr', @house_category_id, 10, NOW(), NOW()),
('File Cab, 4-5 dr', @house_category_id, 20, NOW(), NOW()),
('Files/Papers', @house_category_id, 2, NOW(), NOW()),
('Fireplace Equip.', @house_category_id, 5, NOW(), NOW()),
('Aquarium', @house_category_id, 20, NOW(), NOW()),
('Food', @house_category_id, 4, NOW(), NOW()),
('Footlocker', @house_category_id, 5, NOW(), NOW()),
('Footstool', @house_category_id, 2, NOW(), NOW()),
('Freezer', @house_category_id, 35, NOW(), NOW()),
('Freezer, Large', @house_category_id, 60, NOW(), NOW()),
('Futon', @house_category_id, 25, NOW(), NOW()),
('Games', @house_category_id, 2, NOW(), NOW()),
('Garden Hose/Tool', @house_category_id, 2, NOW(), NOW()),
('Glassware', @house_category_id, 4, NOW(), NOW()),
('Glider - Settee', @house_category_id, 20, NOW(), NOW()),
('Golf Bag & Clubs', @house_category_id, 4, NOW(), NOW()),
('Golf Cart', @house_category_id, 70, NOW(), NOW()),
('Gun Cabinet', @house_category_id, 20, NOW(), NOW()),
('Hat & Coat Stand', @house_category_id, 10, NOW(), NOW()),
('Heater/Radiator', @house_category_id, 5, NOW(), NOW()),
('Chair, High', @house_category_id, 5, NOW(), NOW()),
('Jet Ski', @house_category_id, 60, NOW(), NOW()),
('Ironing Board', @house_category_id, 2, NOW(), NOW()),
('Kitchen Cabinet', @house_category_id, 20, NOW(), NOW()),
('Kitchenware', @house_category_id, 4, NOW(), NOW()),
('Ladder', @house_category_id, 4, NOW(), NOW()),
('Ladder, Step', @house_category_id, 3, NOW(), NOW()),
('Ladder, Extend', @house_category_id, 8, NOW(), NOW()),
('Lamp, Table', @house_category_id, 2, NOW(), NOW()),
('Lamp, Floor', @house_category_id, 3, NOW(), NOW()),
('Lamp, Standard', @house_category_id, 5, NOW(), NOW()),
('Lamp', @house_category_id, 4, NOW(), NOW()),
('Lamp Shade', @house_category_id, 4, NOW(), NOW()),
('Lateral File-2dr', @house_category_id, 30, NOW(), NOW()),
('Lateral File-4dr', @house_category_id, 50, NOW(), NOW()),
('Lawn Edger', @house_category_id, 5, NOW(), NOW()),
('Lawn mower', @house_category_id, 5, NOW(), NOW()),
('Lawn mower,power', @house_category_id, 10, NOW(), NOW()),
('Lawn mower,ridng', @house_category_id, 50, NOW(), NOW()),
('Linen/Towels', @house_category_id, 6, NOW(), NOW()),
('Lounge Suite', @house_category_id, 70, NOW(), NOW()),
('Magazine Rack', @house_category_id, 2, NOW(), NOW()),
('Mat', @house_category_id, 3, NOW(), NOW()),
('Mattress, Single', @house_category_id, 12, NOW(), NOW()),
('Mattress', @house_category_id, 20, NOW(), NOW()),
('Microwave', @house_category_id, 4, NOW(), NOW()),
('Microwave, Cab.', @house_category_id, 10, NOW(), NOW()),
('Mirror', @house_category_id, 2, NOW(), NOW()),
('Moped', @house_category_id, 35, NOW(), NOW()),
('Motor Bike', @house_category_id, 20, NOW(), NOW()),
('Motorcycle', @house_category_id, 70, NOW(), NOW()),
('Organ', @house_category_id, 20, NOW(), NOW()),
('Ornaments', @house_category_id, 2, NOW(), NOW()),
('Ottoman', @house_category_id, 5, NOW(), NOW()),
('Child''s Swing', @house_category_id, 30, NOW(), NOW()),
('Child''s Gym', @house_category_id, 20, NOW(), NOW()),
('Child''s Slide', @house_category_id, 10, NOW(), NOW()),
('Painting', @house_category_id, 2, NOW(), NOW()),
('Partition', @house_category_id, 10, NOW(), NOW()),
('Pedestal', @house_category_id, 10, NOW(), NOW()),
('Photos', @house_category_id, 2, NOW(), NOW()),
('Piano Bench', @house_category_id, 5, NOW(), NOW()),
('Piano, Spinet', @house_category_id, 60, NOW(), NOW()),
('Piano, Upright', @house_category_id, 70, NOW(), NOW()),
('Piano,Baby Grand', @house_category_id, 70, NOW(), NOW()),
('Piano, Grand', @house_category_id, 80, NOW(), NOW()),
('Piano, Concert', @house_category_id, 100, NOW(), NOW()),
('Picnic Bench', @house_category_id, 5, NOW(), NOW()),
('Picnic Table', @house_category_id, 20, NOW(), NOW()),
('Picture/s', @house_category_id, 2, NOW(), NOW()),
('Plant Stand', @house_category_id, 2, NOW(), NOW()),
('Plants', @house_category_id, 3, NOW(), NOW()),
('Plants, Large', @house_category_id, 15, NOW(), NOW()),
('Playpen', @house_category_id, 8, NOW(), NOW()),
('Pool Table,Large', @house_category_id, 100, NOW(), NOW()),
('Pool Table', @house_category_id, 40, NOW(), NOW()),
('Power Tool', @house_category_id, 1, NOW(), NOW()),
('Power Tool Stand', @house_category_id, 3, NOW(), NOW()),
('Baby Carriage', @house_category_id, 4, NOW(), NOW()),
('Printer', @house_category_id, 4, NOW(), NOW()),
('Stroller', @house_category_id, 5, NOW(), NOW()),
('Refrigerator', @house_category_id, 45, NOW(), NOW()),
('Refrig., Large', @house_category_id, 60, NOW(), NOW()),
('Rocker Swing', @house_category_id, 15, NOW(), NOW()),
('Room Divider', @house_category_id, 40, NOW(), NOW()),
('Rug or Pad,Small', @house_category_id, 3, NOW(), NOW()),
('Rug or Pad,Large', @house_category_id, 10, NOW(), NOW()),
('Safe', @house_category_id, 50, NOW(), NOW()),
('Saw Horse', @house_category_id, 5, NOW(), NOW()),
('Sculpture', @house_category_id, 4, NOW(), NOW()),
('Server', @house_category_id, 15, NOW(), NOW()),
('Serving Cart', @house_category_id, 15, NOW(), NOW()),
('Sewing Machine', @house_category_id, 5, NOW(), NOW()),
('Sew Machine,Port', @house_category_id, 5, NOW(), NOW()),
('Sew Machine/Cbnt', @house_category_id, 12, NOW(), NOW()),
('Shelving', @house_category_id, 15, NOW(), NOW()),
('Shoes', @house_category_id, 4, NOW(), NOW()),
('Silver', @house_category_id, 2, NOW(), NOW()),
('Skis', @house_category_id, 3, NOW(), NOW()),
('Sled', @house_category_id, 2, NOW(), NOW()),
('Snowmobile', @house_category_id, 60, NOW(), NOW()),
('Sofa, Ratan', @house_category_id, 10, NOW(), NOW()),
('Snow Blower', @house_category_id, 20, NOW(), NOW()),
('Sofa Section', @house_category_id, 20, NOW(), NOW()),
('Sofa, Loveseat', @house_category_id, 30, NOW(), NOW()),
('Sofa', @house_category_id, 40, NOW(), NOW()),
('Sofa, Hideabed', @house_category_id, 60, NOW(), NOW()),
('Spa/Hot Tub', @house_category_id, 70, NOW(), NOW()),
('Speaker', @house_category_id, 5, NOW(), NOW()),
('Sporting Goods', @house_category_id, 4, NOW(), NOW()),
('Spreader', @house_category_id, 2, NOW(), NOW()),
('Stand', @house_category_id, 2, NOW(), NOW()),
('Statue', @house_category_id, 4, NOW(), NOW()),
('Stereo', @house_category_id, 3, NOW(), NOW()),
('Stereo Component', @house_category_id, 3, NOW(), NOW()),
('Stereo Console', @house_category_id, 15, NOW(), NOW()),
('Stool', @house_category_id, 5, NOW(), NOW()),
('Suitcase', @house_category_id, 5, NOW(), NOW()),
('Table Leaf', @house_category_id, 2, NOW(), NOW()),
('Table, Small', @house_category_id, 2, NOW(), NOW()),
('Table, Bedside', @house_category_id, 5, NOW(), NOW()),
('Table, Child''s', @house_category_id, 5, NOW(), NOW()),
('Table, Coffee', @house_category_id, 5, NOW(), NOW()),
('Table, End', @house_category_id, 5, NOW(), NOW()),
('Table, Utility', @house_category_id, 5, NOW(), NOW()),
('Tables, Nested', @house_category_id, 5, NOW(), NOW()),
('Table', @house_category_id, 10, NOW(), NOW()),
('Table, Drop', @house_category_id, 12, NOW(), NOW()),
('Table, Large', @house_category_id, 25, NOW(), NOW()),
('Ping Pong Table', @house_category_id, 25, NOW(), NOW()),
('Table, Dining', @house_category_id, 30, NOW(), NOW()),
('Table Saw', @house_category_id, 20, NOW(), NOW()),
('Tackle Box', @house_category_id, 2, NOW(), NOW()),
('Tea Cart', @house_category_id, 10, NOW(), NOW()),
('Bathroom Items', @house_category_id, 2, NOW(), NOW()),
('German Schrank 2', @house_category_id, 18, NOW(), NOW()),
('German Schrank 3', @house_category_id, 24, NOW(), NOW()),
('Schrank, 2 Door', @house_category_id, 15, NOW(), NOW()),
('Schrank, 4 Door', @house_category_id, 15, NOW(), NOW()),
('Schrank, 6 Door', @house_category_id, 45, NOW(), NOW()),
('Schrank, sliding', @house_category_id, 40, NOW(), NOW()),
('Tools', @house_category_id, 4, NOW(), NOW()),
('TV Stand', @house_category_id, 3, NOW(), NOW()),
('TV Portable', @house_category_id, 4, NOW(), NOW()),
('TV Tray set', @house_category_id, 4, NOW(), NOW()),
('TV Console', @house_category_id, 15, NOW(), NOW()),
('TV', @house_category_id, 20, NOW(), NOW()),
('TV Big Screen', @house_category_id, 50, NOW(), NOW()),
('Tire', @house_category_id, 3, NOW(), NOW()),
('Toolbox', @house_category_id, 5, NOW(), NOW()),
('Tool Chest', @house_category_id, 15, NOW(), NOW()),
('Tool Shed', @house_category_id, 100, NOW(), NOW()),
('Toy/s', @house_category_id, 10, NOW(), NOW()),
('Trailer', @house_category_id, 100, NOW(), NOW()),
('Trailer >14''', @house_category_id, 115, NOW(), NOW()),
('Trampoline', @house_category_id, 3, NOW(), NOW()),
('Tricycle', @house_category_id, 5, NOW(), NOW()),
('Cart', @house_category_id, 10, NOW(), NOW()),
('Trunk', @house_category_id, 10, NOW(), NOW()),
('Umbrella', @house_category_id, 3, NOW(), NOW()),
('Utility Cabinet', @house_category_id, 10, NOW(), NOW()),
('Vacuum Cleaner', @house_category_id, 5, NOW(), NOW()),
('Valet', @house_category_id, 4, NOW(), NOW()),
('VCR Tapes/CD''s', @house_category_id, 2, NOW(), NOW()),
('Video/VCR', @house_category_id, 2, NOW(), NOW()),
('Video Cabinet', @house_category_id, 5, NOW(), NOW()),
('Wading Pool', @house_category_id, 4, NOW(), NOW()),
('Wagon', @house_category_id, 5, NOW(), NOW()),
('Wall Unit', @house_category_id, 40, NOW(), NOW()),
('Wardrobe', @house_category_id, 40, NOW(), NOW()),
('Washing Machine', @house_category_id, 25, NOW(), NOW()),
('Waste Basket', @house_category_id, 2, NOW(), NOW()),
('Weight Bench', @house_category_id, 5, NOW(), NOW()),
('Weights', @house_category_id, 2, NOW(), NOW()),
('Wheelbarrow', @house_category_id, 5, NOW(), NOW()),
('Wine/Spirits', @house_category_id, 2, NOW(), NOW()),
('Work Bench', @house_category_id, 20, NOW(), NOW()); 